# Generated by Django 6.1.1 on 2026-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True)),
                ('source', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
