# Generated by Django 6.1.1 on 2026-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_image_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
