# Generated by Django 6.1.1 on 2026-10-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_description_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='News',
        ),
    ]
