# Generated by Django 6.1.1 on 2026-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_options_news_created_at_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
